### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by Ari24-cb24** [MauricePascal/AdventofCode#1]
hast du den code von morpheus? Sieht mir ziemlich danach aus

außerdem, mach das repo bitte private oder lad die Lösungen erst am nächsten Tag hoch

dange

**Comment by MauricePascal** [comment]
ja das erste is von morpheus. btw schau dir die Lösung doch dann erst wenn du fertig bist an? xD

**Comment by Ari24-cb24** [comment]
ja vergiss das zweite, was ich geschrieben hatte, war kinda stupid
